version: '3.7'

services:

  root:
    container_name: mfa-root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:80'

  header:
    container_name: mfa-header
    build:
      context: ../header
      dockerfile: Dockerfile
    ports:
      - '9002:80'

  form:
    container_name: mfa-form
    build:
      context: ../form
      dockerfile: Dockerfile
    ports:
      - '9001:80'

networks:
  default:
    name: mfa-net