version: '3.7'

services:

  root:
    container_name: mfa-root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '9000:80'

  header:
    container_name: mfa-header
    build:
      context: ../header
      dockerfile: Dockerfile
    ports:
      - '9002:80'
  
  home:
    container_name: mfa-home
    build:
      context: ../home
      dockerfile: Dockerfile
    ports:
      - '9003:80'

  form:
    container_name: mfa-form
    build:
      context: ../form
      dockerfile: Dockerfile
    ports:
      - '9001:80'

  feed:
    container_name: mfa-feed
    build:
      context: ../feed
      dockerfile: Dockerfile
    ports:
      - '9004:80'

networks:
  default:
    name: mfa-net